-- Test-only, runs after Hibernate builds the H2 schema (Liquibase is off in the test
-- profile). Re-creates what the MySQL migrations give for free: column defaults the
-- entities leave to the DB, and the seed rows migrations 006/013 insert.
ALTER TABLE users              ALTER COLUMN phone_verified      SET DEFAULT FALSE;
ALTER TABLE users              ALTER COLUMN trial_used          SET DEFAULT FALSE;
ALTER TABLE customers          ALTER COLUMN is_deleted          SET DEFAULT FALSE;
ALTER TABLE cars               ALTER COLUMN is_deleted          SET DEFAULT FALSE;
ALTER TABLE bikes              ALTER COLUMN is_deleted          SET DEFAULT FALSE;
ALTER TABLE subscription_plans ALTER COLUMN invoice_generation  SET DEFAULT FALSE;
ALTER TABLE service_order_items ALTER COLUMN discount_amount   SET DEFAULT 0;


-- Every table's audit timestamps default to now, as in the MySQL schema.
ALTER TABLE IF EXISTS allowed_emails ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS allowed_emails ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS bike_brands ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS bike_brands ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS bike_models ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS bike_models ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS bikes ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS bikes ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS car_brands ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS car_brands ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS car_models ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS car_models ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS cars ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS cars ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS customers ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS customers ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS employees ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS employees ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS expense_categories ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS expense_categories ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS expenses ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS expenses ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS feature_properties ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS feature_properties ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS internal_refresh_tokens ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS internal_refresh_tokens ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS org_invites ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS org_invites ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS organizations ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS organizations ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS payment_events ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS payment_events ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS payments ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS payments ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS razorpay_payments ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS razorpay_payments ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS refresh_tokens ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS refresh_tokens ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS service_catalog ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS service_catalog ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS service_categories ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS service_categories ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS service_order_items ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS service_order_items ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS service_orders ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS service_orders ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS subscription_plans ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS subscription_plans ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS subscriptions ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS subscriptions ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS users ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS users ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS vendors ALTER COLUMN IF EXISTS created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS vendors ALTER COLUMN IF EXISTS updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE service_orders     ALTER COLUMN amount_paid         SET DEFAULT 0;
ALTER TABLE service_orders     ALTER COLUMN payment_plan        SET DEFAULT 'one_time';
-- H2's JSON type would store the bound String as a JSON string scalar; keep it plain text.
ALTER TABLE feature_properties ALTER COLUMN property_value      VARCHAR(4000);

INSERT INTO allowed_emails (id, email)
VALUES (RANDOM_UUID(), 'radhaiya.solutions@gmail.com');
INSERT INTO feature_properties (id, property_key, property_value, description)
VALUES (RANDOM_UUID(), 'Client.Maintenance.Mode.Enable', 'false',
        'When true the apps show a full-screen maintenance page and /api/** answers 503');
INSERT INTO feature_properties (id, property_key, property_value, description)
VALUES (RANDOM_UUID(), 'Client.New.Logins.Disabled', 'false',
        'When true brand-new users cannot sign in (existing users still can)');
INSERT INTO feature_properties (id, property_key, property_value, description)
VALUES (RANDOM_UUID(), 'Client.Otp.Verification.Required', 'true',
        'When true phone OTP (to buy a plan) and verified email (at login) are compulsory');
INSERT INTO feature_properties (id, property_key, property_value, description)
VALUES (RANDOM_UUID(), 'Client.Export.SyncExport.Enable', 'false',
        'When true the service-order sync export (Download CSV) is available');
ALTER TABLE subscription_plans ALTER COLUMN amc_enabled SET DEFAULT TRUE;
